# Generated by Django 5.2.14 on 2026-05-10 07:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('text_fr', models.TextField(verbose_name='Question FR')),
                ('text_vi', models.TextField(verbose_name='Question VI')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz_questions/')),
                ('red_text_fr', models.TextField(verbose_name='Réponse rouge FR')),
                ('red_text_vi', models.TextField(verbose_name='Réponse rouge VI')),
                ('blue_text_fr', models.TextField(verbose_name='Réponse bleue FR')),
                ('blue_text_vi', models.TextField(verbose_name='Réponse bleue VI')),
                ('green_text_fr', models.TextField(verbose_name='Réponse verte FR')),
                ('green_text_vi', models.TextField(verbose_name='Réponse verte VI')),
                ('yellow_text_fr', models.TextField(verbose_name='Réponse jaune FR')),
                ('yellow_text_vi', models.TextField(verbose_name='Réponse jaune VI')),
                ('correct_color', models.CharField(choices=[('red', 'Rouge / Đỏ'), ('blue', 'Bleu / Xanh dương'), ('green', 'Vert / Xanh lá'), ('yellow', 'Jaune / Vàng')], max_length=10)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=8, unique=True)),
                ('host_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('current_phase', models.CharField(default='waiting_players', max_length=30)),
                ('phase_started_at', models.DateTimeField(blank=True, null=True)),
                ('phase_duration_ms', models.PositiveIntegerField(default=0)),
                ('answer_duration_seconds', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_quizzes', to='quiz.question')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('session_key', models.CharField(blank=True, max_length=80)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='quiz.quiz')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'Rouge / Đỏ'), ('blue', 'Bleu / Xanh dương'), ('green', 'Vert / Xanh lá'), ('yellow', 'Jaune / Vàng')], max_length=10)),
                ('is_correct', models.BooleanField(default=False)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.player')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'question'), name='one_answer_per_player_per_question')],
            },
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('quiz', 'order'), name='unique_question_order_per_quiz'),
        ),
    ]
