# Generated by Django 5.2.14 on 2026-05-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="language",
            field=models.CharField(
                choices=[("fr", "Français"), ("vi", "Tiếng Việt")],
                default="fr",
                max_length=2,
            ),
        ),
    ]
