# Generated by Django 5.2.14 on 2026-05-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_player_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_read_duration_seconds",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Answer reading duration in seconds"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_read_duration_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Question reading duration in seconds",
            ),
        ),
    ]
